CC=gcc
CFLAGS=-I.
LFLAGS = -lpthread

coins: 
	$(CC) -o coins coins.c $(LFLAGS)






#CC = c compiler
# CFLAGS = -I (used to tell include folders path to compiler)
# -I. ( "." for current directory)
